version: '3.8'

networks:
  demo-network:
    driver: bridge
  es-network:
    driver: bridge

services:
  elasticsearch:
    labels:
      co.elastic.logs/module: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es-network

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - es-network
    ports:
      - '5601:5601'

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es-network

  filebeat:
    depends_on:
      - logstash
      - demoa
      - demob
      - democ
    image: docker.elastic.co/beats/filebeat:7.16.3
    container_name: filebeat
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - es-network
      - demo-network

  democ:
    container_name: demoC-api
    build:
      context: ./demoC
      dockerfile: Dockerfile
    networks:
      - demo-network

  demob:
    depends_on:
      - democ
    container_name: demoB-api
    build:
      context: ./demoB
      dockerfile: Dockerfile
    networks:
      - demo-network

  demoa:
    depends_on:
      - democ
      - demob
    container_name: demoA-api
    build:
      context: ./demoA
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - demo-network